export interface AttributeTypeMap {
  'id': string;
  'xml:base': string;
  'xml:lang': string;
  'xml:space': string;
  'requiredFeatures': string;
  'requiredExtensions': string;
  'systemLanguage': string;
  'xlink:type': string;
  'xlink:role': string;
  'xlink:arcrole': string;
  'xlink:title': string;
  'xlink:show': string;
  'xlink:actuate': string;
  'onfocusin': string;
  'onfocusout': string;
  'onactivate': string;
  'onclick': string;
  'onmousedown': string;
  'onmouseup': string;
  'onmouseover': string;
  'onmousemove': string;
  'onmouseout': string;
  'onload': string;
  'onunload': string;
  'onabort': string;
  'onerror': string;
  'onresize': string;
  'onscroll': string;
  'onzoom': string;
  'onbegin': string;
  'onend': string;
  'onrepeat': string;
  'color': string;
  'color-interpolation': string;
  'color-rendering': string;
  'enable-background': string;
  'flood-color': string;
  'flood-opacity': string | number;
  'color-interpolation-filters': string;
  'fill': string;
  'fill-opacity': string | number;
  'fill-rule': string;
  'stroke': string;
  'stroke-dasharray': string | number[];
  'stroke-dashoffset': string | number;
  'stroke-linecap': string;
  'stroke-linejoin': string;
  'stroke-miterlimit': string | number;
  'stroke-opacity': string | number;
  'stroke-width': string | number;
  'font-family': string;
  'font-size': string | number;
  'font-size-adjust': string | number;
  'font-stretch': string;
  'font-style': string;
  'font-variant': string;
  'font-weight': string;
  'stop-color': string;
  'stop-opacity': string | number;
  'clip-path': string;
  'clip-rule': string;
  'cursor': string;
  'display': string;
  'filter': string;
  'image-rendering': string;
  'mask': string;
  'opacity': string | number;
  'pointer-events': string;
  'shape-rendering': string;
  'text-rendering': string;
  'visibility': string;
  'color-profile': string;
  'lighting-color': string;
  'marker-start': string;
  'marker-mid': string;
  'marker-end': string;
  'alignment-baseline': string;
  'baseline-shift': string | number;
  'direction': string;
  'dominant-baseline': string;
  'glyph-orientation-horizontal': string | number;
  'glyph-orientation-vertical': string | number;
  'letter-spacing': string | number;
  'text-anchor': string;
  'text-decoration': string;
  'unicode-bidi': string;
  'word-spacing': string | number;
  'writing-mode': string;
  'clip': string;
  'overflow': string;
  'x': string | number;
  'y': string | number;
  'width': string | number;
  'height': string | number;
  'result': string;
  'in': string;
  'type': string;
  'tableValues': string;
  'slope': number;
  'intercept': number;
  'amplitude': number;
  'exponent': number;
  'offset': string | number;
  'xlink:href': string;
  'attributeName': string;
  'attributeType': string;
  'begin': string;
  'dur': string;
  'end': string;
  'min': string;
  'max': string;
  'restart': string;
  'repeatCount': string;
  'repeatDur': string;
  'calcMode': string;
  'values': string;
  'keyTimes': string;
  'keySplines': string;
  'from': string;
  'to': string;
  'by': string;
  'additive': string;
  'accumulate': string;
  'externalResourcesRequired': boolean;
  'class': string | string[];
  'style': string;
  'viewBox': string | string[];
  'preserveAspectRatio': string;
  'zoomAndPan': string;
  'contentScriptType': string;
  'contentStyleType': string;
  'transform': string | string[];
  'content': string;
  'media': string;
  'title': string;
  'd': string;
  'pathLength': number;
  'rx': string | number;
  'ry': string | number;
  'cx': string | number;
  'cy': string | number;
  'r': string | number;
  'x1': string | number;
  'y1': string | number;
  'x2': string | number;
  'y2': string | number;
  'points': string | string[];
  'textLength': string | number;
  'lengthAdjust': string;
  'dx': string | number;
  'dy': string | number;
  'rotate': string;
  'startOffset': string;
  'method': string;
  'spacing': string;
  'glyphRef': string;
  'format': string;
  'refX': string | number;
  'refY': string | number;
  'markerUnits': string;
  'markerWidth': string | number;
  'markerHeight': string | number;
  'orient': string;
  'local': string;
  'name': string;
  'rendering-intent': string;
  'gradientUnits': string;
  'gradientTransform': string | string[];
  'spreadMethod': string;
  'fx': string | number;
  'fy': string | number;
  'patternUnits': string;
  'patternTransform': string | string[];
  'clipPathUnits': string;
  'maskUnits': string;
  'filterUnits': string;
  'primitiveUnits': string;
  'filterRes': string;
  'azimuth': number;
  'elevation': number;
  'z': number;
  'pointsAtX': number;
  'pointsAtY': number;
  'pointsAtZ': number;
  'specularExponent': number;
  'limitingConeAngle': number;
  'in2': string;
  'mode': string;
  'operator': string;
  'k1': number;
  'k2': number;
  'k3': number;
  'k4': number;
  'order': string;
  'kernelMatrix': string;
  'divisor': number;
  'bias': number;
  'targetX': number;
  'targetY': number;
  'edgeMode': string;
  'kernelUnitLength': string;
  'preserveAlpha': boolean;
  'surfaceScale': number;
  'diffuseConstant': number;
  'scale': number;
  'xChannelSelector': string;
  'yChannelSelector': string;
  'stdDeviation': string;
  'radius': string | number;
  'specularConstant': number;
  'baseFrequency': string;
  'numOctaves': number;
  'seed': number;
  'stitchTiles': string;
  'target': string;
  'viewTarget': string;
  'path': string;
  'keyPoints': string;
  'origin': string;
  'horiz-origin-x': number;
  'horiz-origin-y': number;
  'horiz-adv-x': number;
  'vert-origin-x': number;
  'vert-origin-y': number;
  'vert-adv-y': number;
  'unicode': string;
  'glyph-name': string;
  'vert-text-orient': string;
  'arabic': string;
  'han': string;
  'u1': string;
  'g1': string;
  'u2': string;
  'g2': string;
  'k': number;
  'unicode-range': string;
  'units-per-em': number;
  'panose-1': string;
  'stemv': number;
  'stemh': number;
  'cap-height': number;
  'x-height': number;
  'accent-height': number;
  'ascent': number;
  'descent': number;
  'widths': string;
  'bbox': string;
  'ideographic': number;
  'baseline': number;
  'centerline': number;
  'mathline': number;
  'hanging': number;
  'topline': number;
  'underline-position': number;
  'underline-thickness': number;
  'strikethrough-position': number;
  'strikethrough-thickness': number;
  'overline-position': number;
  'overline-thickness': number;
  'string': string;
}
